services:
  db:
    image: postgres:18.1-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: veles_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d veles_dev -U postgres']
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data_dev:
