/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCaloriesRouteImport } from './routes/_authenticated/calories'
import { Route as AuthenticatedTodosRouteImport } from './routes/_authenticated/todos'
import { Route as AuthenticatedWeightRouteImport } from './routes/_authenticated/weight'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DemoComponentsRouteImport } from './routes/demo.components'
import { Route as AuthenticatedCaloriesAddRouteImport } from './routes/_authenticated/calories_.add'
import { Route as AuthenticatedCaloriesGoalsRouteImport } from './routes/_authenticated/calories_.goals'
import { Route as AuthenticatedCaloriesQuickAddRouteImport } from './routes/_authenticated/calories_.quick-add'
import { Route as AuthenticatedCaloriesScanRouteImport } from './routes/_authenticated/calories_.scan'
import { Route as AuthenticatedDiaryIndexRouteImport } from './routes/_authenticated/diary/index'
import { Route as AuthenticatedDiaryIdRouteImport } from './routes/_authenticated/diary/$id'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes/index'
import { Route as AuthenticatedRecipesAddRouteImport } from './routes/_authenticated/recipes/add'
import { Route as AuthenticatedWeightAddRouteImport } from './routes/_authenticated/weight_.add'
import { Route as AuthenticatedWeightImportRouteImport } from './routes/_authenticated/weight_.import'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDemoPingRouteImport } from './routes/api/demo/ping'
import { Route as RecipesViewIdRouteImport } from './routes/recipes.view.$id'
import { Route as AuthenticatedCaloriesFoodsFoodIdRouteImport } from './routes/_authenticated/calories_.foods_.$foodId'
import { Route as AuthenticatedCaloriesFoodsNewRouteImport } from './routes/_authenticated/calories_.foods_.new'
import { Route as AuthenticatedCaloriesLogsLogIdRouteImport } from './routes/_authenticated/calories_.logs_.$logId'
import { Route as AuthenticatedRecipesViewIdEditRouteImport } from './routes/_authenticated/recipes/view.$id_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaloriesRoute = AuthenticatedCaloriesRouteImport.update({
  id: '/calories',
  path: '/calories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodosRoute = AuthenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeightRoute = AuthenticatedWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoComponentsRoute = DemoComponentsRouteImport.update({
  id: '/demo/components',
  path: '/demo/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCaloriesAddRoute =
  AuthenticatedCaloriesAddRouteImport.update({
    id: '/calories_/add',
    path: '/calories/add',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaloriesGoalsRoute =
  AuthenticatedCaloriesGoalsRouteImport.update({
    id: '/calories_/goals',
    path: '/calories/goals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaloriesQuickAddRoute =
  AuthenticatedCaloriesQuickAddRouteImport.update({
    id: '/calories_/quick-add',
    path: '/calories/quick-add',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaloriesScanRoute =
  AuthenticatedCaloriesScanRouteImport.update({
    id: '/calories_/scan',
    path: '/calories/scan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiaryIndexRoute = AuthenticatedDiaryIndexRouteImport.update({
  id: '/diary/',
  path: '/diary/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiaryIdRoute = AuthenticatedDiaryIdRouteImport.update({
  id: '/diary/$id',
  path: '/diary/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesAddRoute = AuthenticatedRecipesAddRouteImport.update({
  id: '/recipes/add',
  path: '/recipes/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeightAddRoute = AuthenticatedWeightAddRouteImport.update({
  id: '/weight_/add',
  path: '/weight/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeightImportRoute =
  AuthenticatedWeightImportRouteImport.update({
    id: '/weight_/import',
    path: '/weight/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoPingRoute = ApiDemoPingRouteImport.update({
  id: '/api/demo/ping',
  path: '/api/demo/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesViewIdRoute = RecipesViewIdRouteImport.update({
  id: '/recipes/view/$id',
  path: '/recipes/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCaloriesFoodsFoodIdRoute =
  AuthenticatedCaloriesFoodsFoodIdRouteImport.update({
    id: '/calories_/foods_/$foodId',
    path: '/calories/foods/$foodId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaloriesFoodsNewRoute =
  AuthenticatedCaloriesFoodsNewRouteImport.update({
    id: '/calories_/foods_/new',
    path: '/calories/foods/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaloriesLogsLogIdRoute =
  AuthenticatedCaloriesLogsLogIdRouteImport.update({
    id: '/calories_/logs_/$logId',
    path: '/calories/logs/$logId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesViewIdEditRoute =
  AuthenticatedRecipesViewIdEditRouteImport.update({
    id: '/recipes/view/$id_/edit',
    path: '/recipes/view/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calories': typeof AuthenticatedCaloriesRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/api/health': typeof ApiHealthRoute
  '/demo/components': typeof DemoComponentsRoute
  '/calories/add': typeof AuthenticatedCaloriesAddRoute
  '/calories/goals': typeof AuthenticatedCaloriesGoalsRoute
  '/calories/quick-add': typeof AuthenticatedCaloriesQuickAddRoute
  '/calories/scan': typeof AuthenticatedCaloriesScanRoute
  '/diary/$id': typeof AuthenticatedDiaryIdRoute
  '/recipes/add': typeof AuthenticatedRecipesAddRoute
  '/weight/add': typeof AuthenticatedWeightAddRoute
  '/weight/import': typeof AuthenticatedWeightImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/ping': typeof ApiDemoPingRoute
  '/recipes/view/$id': typeof RecipesViewIdRoute
  '/diary/': typeof AuthenticatedDiaryIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/calories/foods/$foodId': typeof AuthenticatedCaloriesFoodsFoodIdRoute
  '/calories/foods/new': typeof AuthenticatedCaloriesFoodsNewRoute
  '/calories/logs/$logId': typeof AuthenticatedCaloriesLogsLogIdRoute
  '/recipes/view/$id/edit': typeof AuthenticatedRecipesViewIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calories': typeof AuthenticatedCaloriesRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/api/health': typeof ApiHealthRoute
  '/demo/components': typeof DemoComponentsRoute
  '/calories/add': typeof AuthenticatedCaloriesAddRoute
  '/calories/goals': typeof AuthenticatedCaloriesGoalsRoute
  '/calories/quick-add': typeof AuthenticatedCaloriesQuickAddRoute
  '/calories/scan': typeof AuthenticatedCaloriesScanRoute
  '/diary/$id': typeof AuthenticatedDiaryIdRoute
  '/recipes/add': typeof AuthenticatedRecipesAddRoute
  '/weight/add': typeof AuthenticatedWeightAddRoute
  '/weight/import': typeof AuthenticatedWeightImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/ping': typeof ApiDemoPingRoute
  '/recipes/view/$id': typeof RecipesViewIdRoute
  '/diary': typeof AuthenticatedDiaryIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/calories/foods/$foodId': typeof AuthenticatedCaloriesFoodsFoodIdRoute
  '/calories/foods/new': typeof AuthenticatedCaloriesFoodsNewRoute
  '/calories/logs/$logId': typeof AuthenticatedCaloriesLogsLogIdRoute
  '/recipes/view/$id/edit': typeof AuthenticatedRecipesViewIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/calories': typeof AuthenticatedCaloriesRoute
  '/_authenticated/todos': typeof AuthenticatedTodosRoute
  '/_authenticated/weight': typeof AuthenticatedWeightRoute
  '/api/health': typeof ApiHealthRoute
  '/demo/components': typeof DemoComponentsRoute
  '/_authenticated/calories_/add': typeof AuthenticatedCaloriesAddRoute
  '/_authenticated/calories_/goals': typeof AuthenticatedCaloriesGoalsRoute
  '/_authenticated/calories_/quick-add': typeof AuthenticatedCaloriesQuickAddRoute
  '/_authenticated/calories_/scan': typeof AuthenticatedCaloriesScanRoute
  '/_authenticated/diary/$id': typeof AuthenticatedDiaryIdRoute
  '/_authenticated/recipes/add': typeof AuthenticatedRecipesAddRoute
  '/_authenticated/weight_/add': typeof AuthenticatedWeightAddRoute
  '/_authenticated/weight_/import': typeof AuthenticatedWeightImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/ping': typeof ApiDemoPingRoute
  '/recipes/view/$id': typeof RecipesViewIdRoute
  '/_authenticated/diary/': typeof AuthenticatedDiaryIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/calories_/foods_/$foodId': typeof AuthenticatedCaloriesFoodsFoodIdRoute
  '/_authenticated/calories_/foods_/new': typeof AuthenticatedCaloriesFoodsNewRoute
  '/_authenticated/calories_/logs_/$logId': typeof AuthenticatedCaloriesLogsLogIdRoute
  '/_authenticated/recipes/view/$id_/edit': typeof AuthenticatedRecipesViewIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/calories'
    | '/todos'
    | '/weight'
    | '/api/health'
    | '/demo/components'
    | '/calories/add'
    | '/calories/goals'
    | '/calories/quick-add'
    | '/calories/scan'
    | '/diary/$id'
    | '/recipes/add'
    | '/weight/add'
    | '/weight/import'
    | '/api/auth/$'
    | '/api/demo/ping'
    | '/recipes/view/$id'
    | '/diary/'
    | '/recipes/'
    | '/calories/foods/$foodId'
    | '/calories/foods/new'
    | '/calories/logs/$logId'
    | '/recipes/view/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/calories'
    | '/todos'
    | '/weight'
    | '/api/health'
    | '/demo/components'
    | '/calories/add'
    | '/calories/goals'
    | '/calories/quick-add'
    | '/calories/scan'
    | '/diary/$id'
    | '/recipes/add'
    | '/weight/add'
    | '/weight/import'
    | '/api/auth/$'
    | '/api/demo/ping'
    | '/recipes/view/$id'
    | '/diary'
    | '/recipes'
    | '/calories/foods/$foodId'
    | '/calories/foods/new'
    | '/calories/logs/$logId'
    | '/recipes/view/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/calories'
    | '/_authenticated/todos'
    | '/_authenticated/weight'
    | '/api/health'
    | '/demo/components'
    | '/_authenticated/calories_/add'
    | '/_authenticated/calories_/goals'
    | '/_authenticated/calories_/quick-add'
    | '/_authenticated/calories_/scan'
    | '/_authenticated/diary/$id'
    | '/_authenticated/recipes/add'
    | '/_authenticated/weight_/add'
    | '/_authenticated/weight_/import'
    | '/api/auth/$'
    | '/api/demo/ping'
    | '/recipes/view/$id'
    | '/_authenticated/diary/'
    | '/_authenticated/recipes/'
    | '/_authenticated/calories_/foods_/$foodId'
    | '/_authenticated/calories_/foods_/new'
    | '/_authenticated/calories_/logs_/$logId'
    | '/_authenticated/recipes/view/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DemoComponentsRoute: typeof DemoComponentsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDemoPingRoute: typeof ApiDemoPingRoute
  RecipesViewIdRoute: typeof RecipesViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calories': {
      id: '/_authenticated/calories'
      path: '/calories'
      fullPath: '/calories'
      preLoaderRoute: typeof AuthenticatedCaloriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/todos': {
      id: '/_authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthenticatedTodosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weight': {
      id: '/_authenticated/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof AuthenticatedWeightRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/components': {
      id: '/demo/components'
      path: '/demo/components'
      fullPath: '/demo/components'
      preLoaderRoute: typeof DemoComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calories_/add': {
      id: '/_authenticated/calories_/add'
      path: '/calories/add'
      fullPath: '/calories/add'
      preLoaderRoute: typeof AuthenticatedCaloriesAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calories_/goals': {
      id: '/_authenticated/calories_/goals'
      path: '/calories/goals'
      fullPath: '/calories/goals'
      preLoaderRoute: typeof AuthenticatedCaloriesGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calories_/quick-add': {
      id: '/_authenticated/calories_/quick-add'
      path: '/calories/quick-add'
      fullPath: '/calories/quick-add'
      preLoaderRoute: typeof AuthenticatedCaloriesQuickAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calories_/scan': {
      id: '/_authenticated/calories_/scan'
      path: '/calories/scan'
      fullPath: '/calories/scan'
      preLoaderRoute: typeof AuthenticatedCaloriesScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary/': {
      id: '/_authenticated/diary/'
      path: '/diary'
      fullPath: '/diary/'
      preLoaderRoute: typeof AuthenticatedDiaryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary/$id': {
      id: '/_authenticated/diary/$id'
      path: '/diary/$id'
      fullPath: '/diary/$id'
      preLoaderRoute: typeof AuthenticatedDiaryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/add': {
      id: '/_authenticated/recipes/add'
      path: '/recipes/add'
      fullPath: '/recipes/add'
      preLoaderRoute: typeof AuthenticatedRecipesAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weight_/add': {
      id: '/_authenticated/weight_/add'
      path: '/weight/add'
      fullPath: '/weight/add'
      preLoaderRoute: typeof AuthenticatedWeightAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weight_/import': {
      id: '/_authenticated/weight_/import'
      path: '/weight/import'
      fullPath: '/weight/import'
      preLoaderRoute: typeof AuthenticatedWeightImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/ping': {
      id: '/api/demo/ping'
      path: '/api/demo/ping'
      fullPath: '/api/demo/ping'
      preLoaderRoute: typeof ApiDemoPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/view/$id': {
      id: '/recipes/view/$id'
      path: '/recipes/view/$id'
      fullPath: '/recipes/view/$id'
      preLoaderRoute: typeof RecipesViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calories_/foods_/$foodId': {
      id: '/_authenticated/calories_/foods_/$foodId'
      path: '/calories/foods/$foodId'
      fullPath: '/calories/foods/$foodId'
      preLoaderRoute: typeof AuthenticatedCaloriesFoodsFoodIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calories_/foods_/new': {
      id: '/_authenticated/calories_/foods_/new'
      path: '/calories/foods/new'
      fullPath: '/calories/foods/new'
      preLoaderRoute: typeof AuthenticatedCaloriesFoodsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calories_/logs_/$logId': {
      id: '/_authenticated/calories_/logs_/$logId'
      path: '/calories/logs/$logId'
      fullPath: '/calories/logs/$logId'
      preLoaderRoute: typeof AuthenticatedCaloriesLogsLogIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/view/$id_/edit': {
      id: '/_authenticated/recipes/view/$id_/edit'
      path: '/recipes/view/$id/edit'
      fullPath: '/recipes/view/$id/edit'
      preLoaderRoute: typeof AuthenticatedRecipesViewIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCaloriesRoute: typeof AuthenticatedCaloriesRoute
  AuthenticatedTodosRoute: typeof AuthenticatedTodosRoute
  AuthenticatedWeightRoute: typeof AuthenticatedWeightRoute
  AuthenticatedCaloriesAddRoute: typeof AuthenticatedCaloriesAddRoute
  AuthenticatedCaloriesGoalsRoute: typeof AuthenticatedCaloriesGoalsRoute
  AuthenticatedCaloriesQuickAddRoute: typeof AuthenticatedCaloriesQuickAddRoute
  AuthenticatedCaloriesScanRoute: typeof AuthenticatedCaloriesScanRoute
  AuthenticatedDiaryIdRoute: typeof AuthenticatedDiaryIdRoute
  AuthenticatedRecipesAddRoute: typeof AuthenticatedRecipesAddRoute
  AuthenticatedWeightAddRoute: typeof AuthenticatedWeightAddRoute
  AuthenticatedWeightImportRoute: typeof AuthenticatedWeightImportRoute
  AuthenticatedDiaryIndexRoute: typeof AuthenticatedDiaryIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedCaloriesFoodsFoodIdRoute: typeof AuthenticatedCaloriesFoodsFoodIdRoute
  AuthenticatedCaloriesFoodsNewRoute: typeof AuthenticatedCaloriesFoodsNewRoute
  AuthenticatedCaloriesLogsLogIdRoute: typeof AuthenticatedCaloriesLogsLogIdRoute
  AuthenticatedRecipesViewIdEditRoute: typeof AuthenticatedRecipesViewIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCaloriesRoute: AuthenticatedCaloriesRoute,
  AuthenticatedTodosRoute: AuthenticatedTodosRoute,
  AuthenticatedWeightRoute: AuthenticatedWeightRoute,
  AuthenticatedCaloriesAddRoute: AuthenticatedCaloriesAddRoute,
  AuthenticatedCaloriesGoalsRoute: AuthenticatedCaloriesGoalsRoute,
  AuthenticatedCaloriesQuickAddRoute: AuthenticatedCaloriesQuickAddRoute,
  AuthenticatedCaloriesScanRoute: AuthenticatedCaloriesScanRoute,
  AuthenticatedDiaryIdRoute: AuthenticatedDiaryIdRoute,
  AuthenticatedRecipesAddRoute: AuthenticatedRecipesAddRoute,
  AuthenticatedWeightAddRoute: AuthenticatedWeightAddRoute,
  AuthenticatedWeightImportRoute: AuthenticatedWeightImportRoute,
  AuthenticatedDiaryIndexRoute: AuthenticatedDiaryIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedCaloriesFoodsFoodIdRoute: AuthenticatedCaloriesFoodsFoodIdRoute,
  AuthenticatedCaloriesFoodsNewRoute: AuthenticatedCaloriesFoodsNewRoute,
  AuthenticatedCaloriesLogsLogIdRoute: AuthenticatedCaloriesLogsLogIdRoute,
  AuthenticatedRecipesViewIdEditRoute: AuthenticatedRecipesViewIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  DemoComponentsRoute: DemoComponentsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDemoPingRoute: ApiDemoPingRoute,
  RecipesViewIdRoute: RecipesViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
