/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedWeightRouteImport } from './routes/_authenticated/weight'
import { Route as AuthenticatedTodosRouteImport } from './routes/_authenticated/todos'
import { Route as AuthenticatedCaloriesRouteImport } from './routes/_authenticated/calories'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes/index'
import { Route as AuthenticatedDiaryIndexRouteImport } from './routes/_authenticated/diary/index'
import { Route as ApiDemoPingRouteImport } from './routes/api/demo/ping'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedWeightImportRouteImport } from './routes/_authenticated/weight_.import'
import { Route as AuthenticatedWeightAddRouteImport } from './routes/_authenticated/weight_.add'
import { Route as AuthenticatedRecipesAddRouteImport } from './routes/_authenticated/recipes/add'
import { Route as AuthenticatedDiaryIdRouteImport } from './routes/_authenticated/diary/$id'
import { Route as AuthenticatedRecipesViewIdRouteImport } from './routes/_authenticated/recipes/view.$id'
import { Route as AuthenticatedRecipesViewIdEditRouteImport } from './routes/_authenticated/recipes/view.$id_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeightRoute = AuthenticatedWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodosRoute = AuthenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaloriesRoute = AuthenticatedCaloriesRouteImport.update({
  id: '/calories',
  path: '/calories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiaryIndexRoute = AuthenticatedDiaryIndexRouteImport.update({
  id: '/diary/',
  path: '/diary/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiDemoPingRoute = ApiDemoPingRouteImport.update({
  id: '/api/demo/ping',
  path: '/api/demo/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeightImportRoute =
  AuthenticatedWeightImportRouteImport.update({
    id: '/weight_/import',
    path: '/weight/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWeightAddRoute = AuthenticatedWeightAddRouteImport.update({
  id: '/weight_/add',
  path: '/weight/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesAddRoute = AuthenticatedRecipesAddRouteImport.update({
  id: '/recipes/add',
  path: '/recipes/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiaryIdRoute = AuthenticatedDiaryIdRouteImport.update({
  id: '/diary/$id',
  path: '/diary/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesViewIdRoute =
  AuthenticatedRecipesViewIdRouteImport.update({
    id: '/recipes/view/$id',
    path: '/recipes/view/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesViewIdEditRoute =
  AuthenticatedRecipesViewIdEditRouteImport.update({
    id: '/recipes/view/$id_/edit',
    path: '/recipes/view/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calories': typeof AuthenticatedCaloriesRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/api/health': typeof ApiHealthRoute
  '/diary/$id': typeof AuthenticatedDiaryIdRoute
  '/recipes/add': typeof AuthenticatedRecipesAddRoute
  '/weight/add': typeof AuthenticatedWeightAddRoute
  '/weight/import': typeof AuthenticatedWeightImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/ping': typeof ApiDemoPingRoute
  '/diary/': typeof AuthenticatedDiaryIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/recipes/view/$id': typeof AuthenticatedRecipesViewIdRoute
  '/recipes/view/$id/edit': typeof AuthenticatedRecipesViewIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calories': typeof AuthenticatedCaloriesRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/api/health': typeof ApiHealthRoute
  '/diary/$id': typeof AuthenticatedDiaryIdRoute
  '/recipes/add': typeof AuthenticatedRecipesAddRoute
  '/weight/add': typeof AuthenticatedWeightAddRoute
  '/weight/import': typeof AuthenticatedWeightImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/ping': typeof ApiDemoPingRoute
  '/diary': typeof AuthenticatedDiaryIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/recipes/view/$id': typeof AuthenticatedRecipesViewIdRoute
  '/recipes/view/$id/edit': typeof AuthenticatedRecipesViewIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/calories': typeof AuthenticatedCaloriesRoute
  '/_authenticated/todos': typeof AuthenticatedTodosRoute
  '/_authenticated/weight': typeof AuthenticatedWeightRoute
  '/api/health': typeof ApiHealthRoute
  '/_authenticated/diary/$id': typeof AuthenticatedDiaryIdRoute
  '/_authenticated/recipes/add': typeof AuthenticatedRecipesAddRoute
  '/_authenticated/weight_/add': typeof AuthenticatedWeightAddRoute
  '/_authenticated/weight_/import': typeof AuthenticatedWeightImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/ping': typeof ApiDemoPingRoute
  '/_authenticated/diary/': typeof AuthenticatedDiaryIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/recipes/view/$id': typeof AuthenticatedRecipesViewIdRoute
  '/_authenticated/recipes/view/$id_/edit': typeof AuthenticatedRecipesViewIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/calories'
    | '/todos'
    | '/weight'
    | '/api/health'
    | '/diary/$id'
    | '/recipes/add'
    | '/weight/add'
    | '/weight/import'
    | '/api/auth/$'
    | '/api/demo/ping'
    | '/diary/'
    | '/recipes/'
    | '/recipes/view/$id'
    | '/recipes/view/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/calories'
    | '/todos'
    | '/weight'
    | '/api/health'
    | '/diary/$id'
    | '/recipes/add'
    | '/weight/add'
    | '/weight/import'
    | '/api/auth/$'
    | '/api/demo/ping'
    | '/diary'
    | '/recipes'
    | '/recipes/view/$id'
    | '/recipes/view/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/calories'
    | '/_authenticated/todos'
    | '/_authenticated/weight'
    | '/api/health'
    | '/_authenticated/diary/$id'
    | '/_authenticated/recipes/add'
    | '/_authenticated/weight_/add'
    | '/_authenticated/weight_/import'
    | '/api/auth/$'
    | '/api/demo/ping'
    | '/_authenticated/diary/'
    | '/_authenticated/recipes/'
    | '/_authenticated/recipes/view/$id'
    | '/_authenticated/recipes/view/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDemoPingRoute: typeof ApiDemoPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weight': {
      id: '/_authenticated/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof AuthenticatedWeightRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/todos': {
      id: '/_authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthenticatedTodosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calories': {
      id: '/_authenticated/calories'
      path: '/calories'
      fullPath: '/calories'
      preLoaderRoute: typeof AuthenticatedCaloriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary/': {
      id: '/_authenticated/diary/'
      path: '/diary'
      fullPath: '/diary/'
      preLoaderRoute: typeof AuthenticatedDiaryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/demo/ping': {
      id: '/api/demo/ping'
      path: '/api/demo/ping'
      fullPath: '/api/demo/ping'
      preLoaderRoute: typeof ApiDemoPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weight_/import': {
      id: '/_authenticated/weight_/import'
      path: '/weight/import'
      fullPath: '/weight/import'
      preLoaderRoute: typeof AuthenticatedWeightImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weight_/add': {
      id: '/_authenticated/weight_/add'
      path: '/weight/add'
      fullPath: '/weight/add'
      preLoaderRoute: typeof AuthenticatedWeightAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/add': {
      id: '/_authenticated/recipes/add'
      path: '/recipes/add'
      fullPath: '/recipes/add'
      preLoaderRoute: typeof AuthenticatedRecipesAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary/$id': {
      id: '/_authenticated/diary/$id'
      path: '/diary/$id'
      fullPath: '/diary/$id'
      preLoaderRoute: typeof AuthenticatedDiaryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/view/$id': {
      id: '/_authenticated/recipes/view/$id'
      path: '/recipes/view/$id'
      fullPath: '/recipes/view/$id'
      preLoaderRoute: typeof AuthenticatedRecipesViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/view/$id_/edit': {
      id: '/_authenticated/recipes/view/$id_/edit'
      path: '/recipes/view/$id/edit'
      fullPath: '/recipes/view/$id/edit'
      preLoaderRoute: typeof AuthenticatedRecipesViewIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCaloriesRoute: typeof AuthenticatedCaloriesRoute
  AuthenticatedTodosRoute: typeof AuthenticatedTodosRoute
  AuthenticatedWeightRoute: typeof AuthenticatedWeightRoute
  AuthenticatedDiaryIdRoute: typeof AuthenticatedDiaryIdRoute
  AuthenticatedRecipesAddRoute: typeof AuthenticatedRecipesAddRoute
  AuthenticatedWeightAddRoute: typeof AuthenticatedWeightAddRoute
  AuthenticatedWeightImportRoute: typeof AuthenticatedWeightImportRoute
  AuthenticatedDiaryIndexRoute: typeof AuthenticatedDiaryIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedRecipesViewIdRoute: typeof AuthenticatedRecipesViewIdRoute
  AuthenticatedRecipesViewIdEditRoute: typeof AuthenticatedRecipesViewIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCaloriesRoute: AuthenticatedCaloriesRoute,
  AuthenticatedTodosRoute: AuthenticatedTodosRoute,
  AuthenticatedWeightRoute: AuthenticatedWeightRoute,
  AuthenticatedDiaryIdRoute: AuthenticatedDiaryIdRoute,
  AuthenticatedRecipesAddRoute: AuthenticatedRecipesAddRoute,
  AuthenticatedWeightAddRoute: AuthenticatedWeightAddRoute,
  AuthenticatedWeightImportRoute: AuthenticatedWeightImportRoute,
  AuthenticatedDiaryIndexRoute: AuthenticatedDiaryIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedRecipesViewIdRoute: AuthenticatedRecipesViewIdRoute,
  AuthenticatedRecipesViewIdEditRoute: AuthenticatedRecipesViewIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDemoPingRoute: ApiDemoPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
