/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoComponentsRouteImport } from './routes/demo/components'
import { Route as AuthenticatedWeightRouteImport } from './routes/_authenticated/weight'
import { Route as AuthenticatedCaloriesRouteImport } from './routes/_authenticated/calories'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes/index'
import { Route as AuthenticatedDiaryIndexRouteImport } from './routes/_authenticated/diary/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as ApiRecipesUploadRouteImport } from './routes/api/recipes/upload'
import { Route as ApiDemoPingRouteImport } from './routes/api/demo/ping'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedRecipesAddRouteImport } from './routes/_authenticated/recipes/add'
import { Route as AuthenticatedDiaryIdRouteImport } from './routes/_authenticated/diary/$id'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AuthenticatedRecipesViewIdRouteImport } from './routes/_authenticated/recipes/view.$id'
import { Route as AuthenticatedRecipesViewIdEditRouteImport } from './routes/_authenticated/recipes/view.$id_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoComponentsRoute = DemoComponentsRouteImport.update({
  id: '/demo/components',
  path: '/demo/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeightRoute = AuthenticatedWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaloriesRoute = AuthenticatedCaloriesRouteImport.update({
  id: '/calories',
  path: '/calories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiaryIndexRoute = AuthenticatedDiaryIndexRouteImport.update({
  id: '/diary/',
  path: '/diary/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipesUploadRoute = ApiRecipesUploadRouteImport.update({
  id: '/api/recipes/upload',
  path: '/api/recipes/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoPingRoute = ApiDemoPingRouteImport.update({
  id: '/api/demo/ping',
  path: '/api/demo/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecipesAddRoute = AuthenticatedRecipesAddRouteImport.update({
  id: '/recipes/add',
  path: '/recipes/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiaryIdRoute = AuthenticatedDiaryIdRouteImport.update({
  id: '/diary/$id',
  path: '/diary/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecipesViewIdRoute =
  AuthenticatedRecipesViewIdRouteImport.update({
    id: '/recipes/view/$id',
    path: '/recipes/view/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesViewIdEditRoute =
  AuthenticatedRecipesViewIdEditRouteImport.update({
    id: '/recipes/view/$id_/edit',
    path: '/recipes/view/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calories': typeof AuthenticatedCaloriesRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/demo/components': typeof DemoComponentsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/diary/$id': typeof AuthenticatedDiaryIdRoute
  '/recipes/add': typeof AuthenticatedRecipesAddRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/ping': typeof ApiDemoPingRoute
  '/api/recipes/upload': typeof ApiRecipesUploadRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/diary/': typeof AuthenticatedDiaryIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/recipes/view/$id': typeof AuthenticatedRecipesViewIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/recipes/view/$id/edit': typeof AuthenticatedRecipesViewIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calories': typeof AuthenticatedCaloriesRoute
  '/weight': typeof AuthenticatedWeightRoute
  '/demo/components': typeof DemoComponentsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/diary/$id': typeof AuthenticatedDiaryIdRoute
  '/recipes/add': typeof AuthenticatedRecipesAddRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/ping': typeof ApiDemoPingRoute
  '/api/recipes/upload': typeof ApiRecipesUploadRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/diary': typeof AuthenticatedDiaryIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/recipes/view/$id': typeof AuthenticatedRecipesViewIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/recipes/view/$id/edit': typeof AuthenticatedRecipesViewIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/calories': typeof AuthenticatedCaloriesRoute
  '/_authenticated/weight': typeof AuthenticatedWeightRoute
  '/demo/components': typeof DemoComponentsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authenticated/diary/$id': typeof AuthenticatedDiaryIdRoute
  '/_authenticated/recipes/add': typeof AuthenticatedRecipesAddRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/ping': typeof ApiDemoPingRoute
  '/api/recipes/upload': typeof ApiRecipesUploadRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_authenticated/diary/': typeof AuthenticatedDiaryIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/recipes/view/$id': typeof AuthenticatedRecipesViewIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/_authenticated/recipes/view/$id_/edit': typeof AuthenticatedRecipesViewIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/calories'
    | '/weight'
    | '/demo/components'
    | '/demo/tanstack-query'
    | '/diary/$id'
    | '/recipes/add'
    | '/api/auth/$'
    | '/api/demo/ping'
    | '/api/recipes/upload'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/diary/'
    | '/recipes/'
    | '/recipes/view/$id'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/recipes/view/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/calories'
    | '/weight'
    | '/demo/components'
    | '/demo/tanstack-query'
    | '/diary/$id'
    | '/recipes/add'
    | '/api/auth/$'
    | '/api/demo/ping'
    | '/api/recipes/upload'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/diary'
    | '/recipes'
    | '/recipes/view/$id'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/recipes/view/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/calories'
    | '/_authenticated/weight'
    | '/demo/components'
    | '/demo/tanstack-query'
    | '/_authenticated/diary/$id'
    | '/_authenticated/recipes/add'
    | '/api/auth/$'
    | '/api/demo/ping'
    | '/api/recipes/upload'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_authenticated/diary/'
    | '/_authenticated/recipes/'
    | '/_authenticated/recipes/view/$id'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/_authenticated/recipes/view/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  DemoComponentsRoute: typeof DemoComponentsRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDemoPingRoute: typeof ApiDemoPingRoute
  ApiRecipesUploadRoute: typeof ApiRecipesUploadRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/components': {
      id: '/demo/components'
      path: '/demo/components'
      fullPath: '/demo/components'
      preLoaderRoute: typeof DemoComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weight': {
      id: '/_authenticated/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof AuthenticatedWeightRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calories': {
      id: '/_authenticated/calories'
      path: '/calories'
      fullPath: '/calories'
      preLoaderRoute: typeof AuthenticatedCaloriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary/': {
      id: '/_authenticated/diary/'
      path: '/diary'
      fullPath: '/diary/'
      preLoaderRoute: typeof AuthenticatedDiaryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipes/upload': {
      id: '/api/recipes/upload'
      path: '/api/recipes/upload'
      fullPath: '/api/recipes/upload'
      preLoaderRoute: typeof ApiRecipesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/ping': {
      id: '/api/demo/ping'
      path: '/api/demo/ping'
      fullPath: '/api/demo/ping'
      preLoaderRoute: typeof ApiDemoPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recipes/add': {
      id: '/_authenticated/recipes/add'
      path: '/recipes/add'
      fullPath: '/recipes/add'
      preLoaderRoute: typeof AuthenticatedRecipesAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary/$id': {
      id: '/_authenticated/diary/$id'
      path: '/diary/$id'
      fullPath: '/diary/$id'
      preLoaderRoute: typeof AuthenticatedDiaryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recipes/view/$id': {
      id: '/_authenticated/recipes/view/$id'
      path: '/recipes/view/$id'
      fullPath: '/recipes/view/$id'
      preLoaderRoute: typeof AuthenticatedRecipesViewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/view/$id_/edit': {
      id: '/_authenticated/recipes/view/$id_/edit'
      path: '/recipes/view/$id/edit'
      fullPath: '/recipes/view/$id/edit'
      preLoaderRoute: typeof AuthenticatedRecipesViewIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCaloriesRoute: typeof AuthenticatedCaloriesRoute
  AuthenticatedWeightRoute: typeof AuthenticatedWeightRoute
  AuthenticatedDiaryIdRoute: typeof AuthenticatedDiaryIdRoute
  AuthenticatedRecipesAddRoute: typeof AuthenticatedRecipesAddRoute
  AuthenticatedDiaryIndexRoute: typeof AuthenticatedDiaryIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedRecipesViewIdRoute: typeof AuthenticatedRecipesViewIdRoute
  AuthenticatedRecipesViewIdEditRoute: typeof AuthenticatedRecipesViewIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCaloriesRoute: AuthenticatedCaloriesRoute,
  AuthenticatedWeightRoute: AuthenticatedWeightRoute,
  AuthenticatedDiaryIdRoute: AuthenticatedDiaryIdRoute,
  AuthenticatedRecipesAddRoute: AuthenticatedRecipesAddRoute,
  AuthenticatedDiaryIndexRoute: AuthenticatedDiaryIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedRecipesViewIdRoute: AuthenticatedRecipesViewIdRoute,
  AuthenticatedRecipesViewIdEditRoute: AuthenticatedRecipesViewIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  DemoComponentsRoute: DemoComponentsRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDemoPingRoute: ApiDemoPingRoute,
  ApiRecipesUploadRoute: ApiRecipesUploadRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
